docs:
  - all:
    - changed-files:
      - all-globs-to-all-files:
        - '**/*.md'

internal:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - .github/**
        - scripts/**
        - .gitignore
        - .pre-commit-config.yaml
      - all-globs-to-all-files:
        - '**/*.md'
        - 'frontend/**'
        - 'backend/**'
